# Generated by Django 3.2.4 on 2021-06-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=200, verbose_name='функция')),
                ('interval', models.PositiveIntegerField(default=5, verbose_name='интервал t, дней')),
                ('step', models.PositiveIntegerField(default=1, verbose_name='шаг t, часы')),
                ('last_date', models.DateTimeField(auto_now_add=True, verbose_name='дата обработки')),
                ('plot', models.ImageField(blank=True, null=True, upload_to='funcapp/', verbose_name='график')),
                ('errorfield', models.CharField(max_length=200, verbose_name='ошибка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
